### ISSUE TITLE
Test cases last newline issue

### ISSUE THREAD

**Issue by nganhkhoa** [fukamachi/getac#4]
I found out an unintended bug, if the last Test has an endline character, it will fail with

```
TYPE-ERROR: The value
              NIL
            is not of type
              REAL
```

Make it clear in the document that all tests are last-endline expected, and the test file has no empty lines at the bottom.

I also think that we should ignore the last endline of the output, it is often not important to fail a test case.

**Comment by fukamachi** [comment]
Thank you for reporting. Should be fixed in a few days.

**Comment by fukamachi** [comment]
Fixed at https://github.com/fukamachi/getac/commit/512f9b4a15219b150e56383577919dfdd26de808.
